Import('qt_env', 'arch', 'common', 'messaging', 'visionipc', 'cereal', 'transformations')

map_env = qt_env.Clone()
wsl2 = bool(qt_env.get("IS_WSL2", False))

libs = ['qt_widgets', 'qt_util', 'QMapLibre', common, messaging, cereal, visionipc, transformations,
        'zmq', 'capnp', 'kj', 'm', 'OpenCL', 'ssl', 'crypto', 'pthread', 'json11'] + map_env["LIBS"]
if arch == 'larch64':
  libs.append(':libEGL_mesa.so.0')

if arch in ['larch64', 'aarch64', 'x86_64'] and not wsl2:
  if arch == 'x86_64':
    rpath = Dir(f"#third_party/maplibre-native-qt/{arch}/lib").srcnode().abspath
    map_env["RPATH"] += [rpath, ]

  style_path = File("style.json").abspath
  map_env['CXXFLAGS'].append(f'-DSTYLE_PATH=\\"{style_path}\\"')

  map_env["RPATH"].append(Dir('.').abspath)
  map_env["LIBPATH"].append(Dir('.').abspath)
  maplib = map_env.SharedLibrary("maprender", ["map_renderer.cc"], LIBS=libs)
  map_env.Program("mapsd", ["main.cc", ], LIBS=[maplib[0].get_path(), ] + libs)
elif wsl2:
  print("Building for WSL2. Skipping navd map renderer build")
